### PR TITLE
Fix PyGIWarning

### PR DESCRIPTION
**Pull request by Hrishi1999**
Fixed warnings for GTK and Vte

### CODE REVIEW

**Review by Aniket21mathur — CHANGES_REQUESTED** [review]
Thanks @Hrishi1999 reviewed tested.The following change can also be made:

- [ ] Also fix this deprecation warning.
`1548565304.020593 ERROR root: ATTENTION: service_name property in the activity.info file is deprecated, should be  changed to bundle_id`

**Comment by Hrishi1999** [comment]
@Aniket21mathur Done :)

**Comment by Aniket21mathur** [comment]
Thanks @Hrishi1999. Reviewed , looks good to go :)

**Review by Aniket21mathur — APPROVED** [review]

**Comment by quozl** [comment]
Discarded b958edd70f8a93511dee331b0a2a27df349f2824.  Fix https://github.com/sugarlabs/riverhex-activity/issues/5 first, thanks.

**Pull request merged**
